version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: .  # Set the build context to the root
      dockerfile: backend/Dockerfile  # Specify the Dockerfile for the backend
    container_name: backend-container
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo

  frontend:
    build:
      context: .  # Set the build context to the root
      dockerfile: frontend/Dockerfile  # Specify the Dockerfile for the frontend
    container_name: frontend-container
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data:
